//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub use super::article::Entity as Article;
pub use super::category::Entity as Category;
pub use super::category_article::Entity as CategoryArticle;
pub use super::image::Entity as Image;
pub use super::tag::Entity as Tag;
pub use super::tag_article::Entity as TagArticle;
